services:
  client:
    build: .
    container_name: medialab-client
    ports:
      - "4810:4810"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes:ro
      - ./:/app
      - /tmp:/stack-data
    environment:
      - HOST_URL=http://192.168.10.30:4810
      - SERVER_URL=http://192.168.10.10:4800
      - RESTIC_SERVER=http://192.168.10.10:4500
      - STACK_BACKUP_CRON_MINUTE=1
      - STACK_BACKUP_CRON_HOUR=2
      - STACK_BACKUP_CRON_SECOND=3
      - STACK_BACKUP_ENABLE=true
      - RESTIC_REPO=rest:http://192.168.10.10:4500/
      - RESTIC_PASSWORD=media
    restart: unless-stopped

  test-dummy:
    image: nginx:alpine
    container_name: test-dummy
    ports:
      - "8080:80"
    restart: unless-stopped 
    labels:
      - "medialab-client.full-backup=true"
  