version: '3.8'

services:
  client:
    build: .
    container_name: medialab-client
    ports:
      - "4810:4810"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes:ro
      - ./:/app
    environment:
      - SERVER_HOST=192.168.10.10
      - SERVER_PORT=4800
      - RESTIC_SERVER=192.168.10.10:4500
      - STACK_BACKUP_CRON_MINS=*
      - STACK_BACKUP_CRON_HOURS=*
      - STACK_BACKUP_CRON_SECS=*/10
      - STACK_BACKUP_ENABLE=true
      - RESTIC_PATH=/var/lib/docker/volumes
      - RESTIC_REPO=rest:http://192.168.10.10:4500/backup
      - RESTIC_PASSWORD=media
    restart: unless-stopped

  test-dummy:
    image: nginx:alpine
    container_name: test-dummy
    ports:
      - "8080:80"
    restart: unless-stopped 
    labels:
      - "medialab-client.full-backup=true"