version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medialab-server
    ports:
      - "4800:4800"
    environment:
      - ENVIRONMENT=development
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config.json:/app/config.json
    restart: unless-stopped 