version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: medialab-client
    ports:
      - "4810:4810"
    environment:
      - ENVIRONMENT=development
    volumes:
      - ./client:/app
    restart: unless-stopped 