version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: medialab-server-dev
    ports:
      - "4800:4800"
    environment:
      - ENVIRONMENT=development
      - PYTHONPATH=/app
      - DEBUG=1
    volumes:
      - .:/app
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config.json:/app/config.json
    command: uvicorn app.main:app --host 0.0.0.0 --port 4800 --reload
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: medialab-client-dev
    ports:
      - "4810:4810"
    environment:
      - ENVIRONMENT=development
      - HOST_URL=http://localhost:4810
      - SERVER_URL=http://server:4800
      - DEBUG=1
    volumes:
      - ./client:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes:ro
    command: uvicorn main:app --host 0.0.0.0 --port 4810 --reload
    depends_on:
      - server
    restart: unless-stopped 